# Generated by Django 5.2.10 on 2026-04-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('promo', 'Promo / Offer'), ('alert', 'Alert'), ('update', 'Update')], default='info', max_length=20)),
                ('icon', models.CharField(default='bell', help_text='Lucide icon name e.g. bell, tag, zap, info', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank to never expire', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='inquiry', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bookings', to='trips.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('days', models.PositiveIntegerField()),
                ('nights', models.PositiveIntegerField()),
                ('banner_image', models.ImageField(upload_to='package_banners/')),
                ('accommodation_type', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('dorm', 'Dorm'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('houseboat', 'Houseboat')], max_length=20)),
                ('accommodation_description', models.TextField()),
                ('accommodation_image', models.ImageField(upload_to='package_accommodations/')),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('meals_included', models.CharField(choices=[('breakfast', 'Breakfast Only'), ('breakfast_dinner', 'Breakfast + Dinner'), ('all_meals', 'All Meals'), ('none', 'No Meals')], default='breakfast', max_length=50)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_couple', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_charges', models.TextField(blank=True)),
                ('include_local_guide', models.BooleanField(default=False)),
                ('whatsapp_support', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.appuser')),
            ],
            options={
                'ordering': ['-avg_rating', '-total_bookings'],
            },
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(max_length=255)),
                ('review_text', models.TextField(max_length=1000)),
                ('accommodation_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('guide_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('experience_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('review_photo', models.ImageField(blank=True, upload_to='package_reviews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='trips.packagebooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_reviews', to='trips.appuser')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.travelpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='package_experiences/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='trips.travelpackage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.travelpackage'),
        ),
        migrations.CreateModel(
            name='PackageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=False)),
                ('extra_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.travelpackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meals', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.travelpackage')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('package', 'day')},
            },
        ),
    ]
