# Generated by Django 5.2.10 on 2026-04-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('travel_distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('travel_time', models.CharField(blank=True, max_length=100, null=True)),
                ('stay_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_location', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('base_price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='package_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='packageexperience',
            name='package',
        ),
        migrations.AlterUniqueTogether(
            name='packageitinerary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='packageitinerary',
            name='package',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='packagereview',
            options={},
        ),
        migrations.AlterField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='bell', max_length=50),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='accommodation_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='experience_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='guide_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='review_text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ItineraryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.dayitinerary')),
            ],
        ),
        migrations.CreateModel(
            name='PricingBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stay_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activity_cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_person_calculated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='trips.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageIncludeExclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes_excludes', to='trips.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='trips.tourpackage')),
            ],
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.tourpackage'),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourpackage'),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trips.tourpackage'),
        ),
        migrations.DeleteModel(
            name='PackageActivity',
        ),
        migrations.DeleteModel(
            name='PackageExperience',
        ),
        migrations.DeleteModel(
            name='PackageItinerary',
        ),
        migrations.DeleteModel(
            name='TravelPackage',
        ),
    ]
