# Generated by Django 5.2.10 on 2026-07-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_category_herobanner_tourpackage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nearby_landmark', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('distance_km', models.PositiveIntegerField(default=75)),
                ('cover_image', models.ImageField(upload_to='hidden_spots/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='hidden_spots/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='hidden_spots/')),
                ('avg_rating', models.FloatField(default=4.7)),
                ('reviews_count', models.PositiveIntegerField(default=12)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_spots', to='trips.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
