# Generated by Django 5.2.10 on 2026-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_hiddenspot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload category icon image (20x20 or thumbnail)', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Lucide icon name (e.g., 'palmtree')", max_length=50),
        ),
    ]
