# Generated by Django 5.2.10 on 2026-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Solo, Couple Or Friends - We Have Trips for All', max_length=255)),
                ('subtitle', models.TextField(blank=True, default="Most travellers don't just travel with us, they meet strangers who quickly turn into their people.")),
                ('image', models.ImageField(blank=True, help_text='Upload custom Banner 2 image', null=True, upload_to='banners/')),
                ('button_text', models.CharField(blank=True, default='Explore Trips', max_length=50)),
                ('link_to', models.CharField(blank=True, default='/packages', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Secondary Banner (Under Why Tripik)',
                'verbose_name_plural': 'Secondary Banners (Under Why Tripik)',
            },
        ),
    ]
