# Generated by Django 5.2.10 on 2026-07-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_secondarybanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(default='Travel Guide', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('cover_image', models.ImageField(upload_to='blogs/')),
                ('excerpt', models.TextField(help_text='Short summary displayed on cards')),
                ('content', models.TextField(help_text='Full blog post content')),
                ('author_name', models.CharField(default='Tripik Team', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
