# Generated by Django 5.2.10 on 2026-07-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_faqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_bookings', to='trips.appuser'),
        ),
    ]
