# Generated by Django 5.2.10 on 2026-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_packagereview_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='ANNOUNCEMENT', max_length=50)),
                ('message', models.TextField(default='🎉 Special Launch Offer: Book your Kashmir & Kerala group departure with zero booking fees!')),
                ('link_url', models.CharField(blank=True, help_text='Optional relative or full URL link', max_length=255, null=True)),
                ('bg_color', models.CharField(default='#b45309', help_text='HEX or CSS background color', max_length=50)),
                ('text_color', models.CharField(default='#ffffff', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bars',
                'ordering': ['-created_at'],
            },
        ),
    ]
